version: '3.3'
services:
  # Postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  web:
    build: .
    # command: ["./run_web.sh"]
    environment:
      - DOCKER_HOST=postgres
    command: python3 my_app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/my_app
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - postgres
