# Generated by Django 2.1.3 on 2018-12-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=9, verbose_name='gender'),
        ),
    ]
