# Generated by Django 2.1.3 on 2018-11-30 02:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.CharField(editable=False, max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=200)),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Phonto')),
                ('lat', models.FloatField(verbose_name='Latitude')),
                ('lng', models.FloatField(verbose_name='Longitude')),
                ('tip_count', models.IntegerField(verbose_name='Tip count')),
                ('users_count', models.IntegerField(verbose_name='Users count')),
                ('checkins_count', models.IntegerField(verbose_name='Check-ins count')),
                ('visits_count', models.IntegerField(verbose_name='Visits count')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date of the last update')),
                ('added_by', models.ForeignKey(on_delete='DO_NOTHING', related_name='added_by', to=settings.AUTH_USER_MODEL, verbose_name='Added by')),
            ],
        ),
    ]
