# Generated by Django 2.1.3 on 2018-11-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Phonto'),
        ),
    ]
