
# Development keys

FOURSQUARE = {
    'CLIENT_ID': 'TZ3WMGRJK1HQTQS4KHLQERZVMN0O0LWHY0CRFHXDZPWY0DPT',
    'CLIENT_SECRET': '1XBYD3GHHFDII3D0LREUTJZCMTFB5KHUZYW1A5OM0ZMBHHAC',
    'REDIRECT_URL': 'http://fondu.com/oauth/authorize'
}
